// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file workflow.proto (package n8nwork.workflow.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelExecutionRequest, CancelExecutionResponse, CreateWorkflowRequest, CreateWorkflowResponse, DeleteWorkflowRequest, DeleteWorkflowResponse, GetExecutionRequest, GetExecutionResponse, GetWorkflowRequest, GetWorkflowResponse, ListExecutionsRequest, ListExecutionsResponse, ListWorkflowsRequest, ListWorkflowsResponse, StartExecutionRequest, StartExecutionResponse, UpdateWorkflowRequest, UpdateWorkflowResponse } from "./workflow_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Workflow management service
 *
 * @generated from service n8nwork.workflow.v1.WorkflowService
 */
export const WorkflowService = {
  typeName: "n8nwork.workflow.v1.WorkflowService",
  methods: {
    /**
     * Create a new workflow
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.CreateWorkflow
     */
    createWorkflow: {
      name: "CreateWorkflow",
      I: CreateWorkflowRequest,
      O: CreateWorkflowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get workflow by ID
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.GetWorkflow
     */
    getWorkflow: {
      name: "GetWorkflow",
      I: GetWorkflowRequest,
      O: GetWorkflowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update existing workflow
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.UpdateWorkflow
     */
    updateWorkflow: {
      name: "UpdateWorkflow",
      I: UpdateWorkflowRequest,
      O: UpdateWorkflowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete workflow
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.DeleteWorkflow
     */
    deleteWorkflow: {
      name: "DeleteWorkflow",
      I: DeleteWorkflowRequest,
      O: DeleteWorkflowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List workflows
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.ListWorkflows
     */
    listWorkflows: {
      name: "ListWorkflows",
      I: ListWorkflowsRequest,
      O: ListWorkflowsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Start workflow execution
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.StartExecution
     */
    startExecution: {
      name: "StartExecution",
      I: StartExecutionRequest,
      O: StartExecutionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get execution details
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.GetExecution
     */
    getExecution: {
      name: "GetExecution",
      I: GetExecutionRequest,
      O: GetExecutionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List executions
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.ListExecutions
     */
    listExecutions: {
      name: "ListExecutions",
      I: ListExecutionsRequest,
      O: ListExecutionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Cancel execution
     *
     * @generated from rpc n8nwork.workflow.v1.WorkflowService.CancelExecution
     */
    cancelExecution: {
      name: "CancelExecution",
      I: CancelExecutionRequest,
      O: CancelExecutionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

