receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8889']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  resource:
    attributes:
      - key: service.name
        action: upsert
        from_attribute: service_name
      - key: service.version
        action: upsert
        from_attribute: service_version

  memory_limiter:
    limit_mib: 400

exporters:
  # Traces to Tempo
  otlp/tempo:
    endpoint: http://tempo:3200
    tls:
      insecure: true

  # Logs to Loki
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tenant_id: "n8n-work"

  # Metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Debug logging
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp/tempo, logging]

    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, logging]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [loki, logging]

  extensions: []
