apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook
  labels:
    app: alertmanager-webhook
    component: observability
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alertmanager-webhook
  template:
    metadata:
      labels:
        app: alertmanager-webhook
    spec:
      containers:
        - name: webhook
          image: prom/alertmanager-webhook-logger:latest
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          env:
            - name: PORT
              value: "9093"
            - name: LOG_LEVEL
              value: "info"
          livenessProbe:
            httpGet:
              path: /health
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9093
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webhook
  labels:
    app: alertmanager-webhook
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: http
  selector:
    app: alertmanager-webhook
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-webhook-config
data:
  config.yaml: |
    webhooks:
      critical:
        url: "http://alertmanager-webhook:9093/hooks/critical"
        method: POST
        headers:
          Content-Type: application/json
        template: |
          {
            "text": "🚨 CRITICAL ALERT: {{ .GroupLabels.alertname }}",
            "attachments": [
              {
                "color": "danger",
                "fields": [
                  {
                    "title": "Alert",
                    "value": "{{ .GroupLabels.alertname }}",
                    "short": true
                  },
                  {
                    "title": "Status",
                    "value": "{{ .Status }}",
                    "short": true
                  }
                ]
              }
            ]
          }
      warning:
        url: "http://alertmanager-webhook:9093/hooks/warning"
        method: POST
        headers:
          Content-Type: application/json
        template: |
          {
            "text": "⚠️ WARNING: {{ .GroupLabels.alertname }}",
            "attachments": [
              {
                "color": "warning",
                "fields": [
                  {
                    "title": "Alert",
                    "value": "{{ .GroupLabels.alertname }}",
                    "short": true
                  },
                  {
                    "title": "Status",
                    "value": "{{ .Status }}",
                    "short": true
                  }
                ]
              }
            ]
          }