// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: execution.proto

package executionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error classification for handling
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED   ErrorCode = 0
	ErrorCode_ERROR_CODE_NONE          ErrorCode = 1
	ErrorCode_ERROR_CODE_TRANSIENT     ErrorCode = 2
	ErrorCode_ERROR_CODE_FATAL         ErrorCode = 3
	ErrorCode_ERROR_CODE_TIMEOUT       ErrorCode = 4
	ErrorCode_ERROR_CODE_CANCELLED     ErrorCode = 5
	ErrorCode_ERROR_CODE_RATE_LIMIT    ErrorCode = 6
	ErrorCode_ERROR_CODE_AUTHORIZATION ErrorCode = 7
	ErrorCode_ERROR_CODE_INVALID_INPUT ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_NONE",
		2: "ERROR_CODE_TRANSIENT",
		3: "ERROR_CODE_FATAL",
		4: "ERROR_CODE_TIMEOUT",
		5: "ERROR_CODE_CANCELLED",
		6: "ERROR_CODE_RATE_LIMIT",
		7: "ERROR_CODE_AUTHORIZATION",
		8: "ERROR_CODE_INVALID_INPUT",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":   0,
		"ERROR_CODE_NONE":          1,
		"ERROR_CODE_TRANSIENT":     2,
		"ERROR_CODE_FATAL":         3,
		"ERROR_CODE_TIMEOUT":       4,
		"ERROR_CODE_CANCELLED":     5,
		"ERROR_CODE_RATE_LIMIT":    6,
		"ERROR_CODE_AUTHORIZATION": 7,
		"ERROR_CODE_INVALID_INPUT": 8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_execution_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

// Data classification for compliance
type DataClass int32

const (
	DataClass_DATA_CLASS_UNSPECIFIED DataClass = 0
	DataClass_DATA_CLASS_GENERIC     DataClass = 1
	DataClass_DATA_CLASS_PII         DataClass = 2
	DataClass_DATA_CLASS_PHI         DataClass = 3
	DataClass_DATA_CLASS_SECRET      DataClass = 4
	DataClass_DATA_CLASS_FINANCIAL   DataClass = 5
)

// Enum value maps for DataClass.
var (
	DataClass_name = map[int32]string{
		0: "DATA_CLASS_UNSPECIFIED",
		1: "DATA_CLASS_GENERIC",
		2: "DATA_CLASS_PII",
		3: "DATA_CLASS_PHI",
		4: "DATA_CLASS_SECRET",
		5: "DATA_CLASS_FINANCIAL",
	}
	DataClass_value = map[string]int32{
		"DATA_CLASS_UNSPECIFIED": 0,
		"DATA_CLASS_GENERIC":     1,
		"DATA_CLASS_PII":         2,
		"DATA_CLASS_PHI":         3,
		"DATA_CLASS_SECRET":      4,
		"DATA_CLASS_FINANCIAL":   5,
	}
)

func (x DataClass) Enum() *DataClass {
	p := new(DataClass)
	*p = x
	return p
}

func (x DataClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataClass) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_proto_enumTypes[1].Descriptor()
}

func (DataClass) Type() protoreflect.EnumType {
	return &file_execution_proto_enumTypes[1]
}

func (x DataClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataClass.Descriptor instead.
func (DataClass) EnumDescriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

type GetExecutionStatusResponse_Status int32

const (
	GetExecutionStatusResponse_STATUS_UNSPECIFIED GetExecutionStatusResponse_Status = 0
	GetExecutionStatusResponse_STATUS_PENDING     GetExecutionStatusResponse_Status = 1
	GetExecutionStatusResponse_STATUS_RUNNING     GetExecutionStatusResponse_Status = 2
	GetExecutionStatusResponse_STATUS_COMPLETED   GetExecutionStatusResponse_Status = 3
	GetExecutionStatusResponse_STATUS_FAILED      GetExecutionStatusResponse_Status = 4
	GetExecutionStatusResponse_STATUS_CANCELLED   GetExecutionStatusResponse_Status = 5
	GetExecutionStatusResponse_STATUS_TIMEOUT     GetExecutionStatusResponse_Status = 6
)

// Enum value maps for GetExecutionStatusResponse_Status.
var (
	GetExecutionStatusResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_RUNNING",
		3: "STATUS_COMPLETED",
		4: "STATUS_FAILED",
		5: "STATUS_CANCELLED",
		6: "STATUS_TIMEOUT",
	}
	GetExecutionStatusResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_RUNNING":     2,
		"STATUS_COMPLETED":   3,
		"STATUS_FAILED":      4,
		"STATUS_CANCELLED":   5,
		"STATUS_TIMEOUT":     6,
	}
)

func (x GetExecutionStatusResponse_Status) Enum() *GetExecutionStatusResponse_Status {
	p := new(GetExecutionStatusResponse_Status)
	*p = x
	return p
}

func (x GetExecutionStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetExecutionStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_proto_enumTypes[2].Descriptor()
}

func (GetExecutionStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_execution_proto_enumTypes[2]
}

func (x GetExecutionStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetExecutionStatusResponse_Status.Descriptor instead.
func (GetExecutionStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{8, 0}
}

type HealthResponse_Status int32

const (
	HealthResponse_STATUS_UNSPECIFIED     HealthResponse_Status = 0
	HealthResponse_STATUS_SERVING         HealthResponse_Status = 1
	HealthResponse_STATUS_NOT_SERVING     HealthResponse_Status = 2
	HealthResponse_STATUS_SERVICE_UNKNOWN HealthResponse_Status = 3
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SERVING",
		2: "STATUS_NOT_SERVING",
		3: "STATUS_SERVICE_UNKNOWN",
	}
	HealthResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":     0,
		"STATUS_SERVING":         1,
		"STATUS_NOT_SERVING":     2,
		"STATUS_SERVICE_UNKNOWN": 3,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_proto_enumTypes[3].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_execution_proto_enumTypes[3]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{12, 0}
}

// Retry policy configuration
type RetryPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts   int32                  `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"` // "exponential", "linear", "fixed"
	BaseDelayMs   int64                  `protobuf:"varint,3,opt,name=base_delay_ms,json=baseDelayMs,proto3" json:"base_delay_ms,omitempty"`
	JitterFactor  float64                `protobuf:"fixed64,4,opt,name=jitter_factor,json=jitterFactor,proto3" json:"jitter_factor,omitempty"`
	MaxDelayMs    int64                  `protobuf:"varint,5,opt,name=max_delay_ms,json=maxDelayMs,proto3" json:"max_delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

func (x *RetryPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *RetryPolicy) GetBaseDelayMs() int64 {
	if x != nil {
		return x.BaseDelayMs
	}
	return 0
}

func (x *RetryPolicy) GetJitterFactor() float64 {
	if x != nil {
		return x.JitterFactor
	}
	return 0
}

func (x *RetryPolicy) GetMaxDelayMs() int64 {
	if x != nil {
		return x.MaxDelayMs
	}
	return 0
}

// Step execution policy
type StepPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs       int64                  `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	RetryPolicy     *RetryPolicy           `protobuf:"bytes,2,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	ContinueOnError bool                   `protobuf:"varint,3,opt,name=continue_on_error,json=continueOnError,proto3" json:"continue_on_error,omitempty"`
	Environment     map[string]string      `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StepPolicy) Reset() {
	*x = StepPolicy{}
	mi := &file_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepPolicy) ProtoMessage() {}

func (x *StepPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepPolicy.ProtoReflect.Descriptor instead.
func (*StepPolicy) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

func (x *StepPolicy) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *StepPolicy) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *StepPolicy) GetContinueOnError() bool {
	if x != nil {
		return x.ContinueOnError
	}
	return false
}

func (x *StepPolicy) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

// File artifact reference
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	DataClass     DataClass              `protobuf:"varint,3,opt,name=data_class,json=dataClass,proto3,enum=n8nwork.execution.v1.DataClass" json:"data_class,omitempty"`
	Bytes         int64                  `protobuf:"varint,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{2}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Artifact) GetDataClass() DataClass {
	if x != nil {
		return x.DataClass
	}
	return DataClass_DATA_CLASS_UNSPECIFIED
}

func (x *Artifact) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Artifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Artifact) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Log line from step execution
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // "debug", "info", "warn", "error"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{3}
}

func (x *LogLine) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Runtime capabilities reported by node runner
type Capabilities struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SupportsAsyncNodes       bool                   `protobuf:"varint,1,opt,name=supports_async_nodes,json=supportsAsyncNodes,proto3" json:"supports_async_nodes,omitempty"`
	SupportsWasm             bool                   `protobuf:"varint,2,opt,name=supports_wasm,json=supportsWasm,proto3" json:"supports_wasm,omitempty"`
	SupportsMicrovm          bool                   `protobuf:"varint,3,opt,name=supports_microvm,json=supportsMicrovm,proto3" json:"supports_microvm,omitempty"`
	AllowedEgressDomains     []string               `protobuf:"bytes,4,rep,name=allowed_egress_domains,json=allowedEgressDomains,proto3" json:"allowed_egress_domains,omitempty"`
	SupportedIsolationLevels []string               `protobuf:"bytes,5,rep,name=supported_isolation_levels,json=supportedIsolationLevels,proto3" json:"supported_isolation_levels,omitempty"`
	RuntimeInfo              map[string]string      `protobuf:"bytes,6,rep,name=runtime_info,json=runtimeInfo,proto3" json:"runtime_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{4}
}

func (x *Capabilities) GetSupportsAsyncNodes() bool {
	if x != nil {
		return x.SupportsAsyncNodes
	}
	return false
}

func (x *Capabilities) GetSupportsWasm() bool {
	if x != nil {
		return x.SupportsWasm
	}
	return false
}

func (x *Capabilities) GetSupportsMicrovm() bool {
	if x != nil {
		return x.SupportsMicrovm
	}
	return false
}

func (x *Capabilities) GetAllowedEgressDomains() []string {
	if x != nil {
		return x.AllowedEgressDomains
	}
	return nil
}

func (x *Capabilities) GetSupportedIsolationLevels() []string {
	if x != nil {
		return x.SupportedIsolationLevels
	}
	return nil
}

func (x *Capabilities) GetRuntimeInfo() map[string]string {
	if x != nil {
		return x.RuntimeInfo
	}
	return nil
}

// Step execution request
type StepExecRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId    string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepId   string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	NodeType string                 `protobuf:"bytes,4,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	// Input data as JSON
	InputJson []byte `protobuf:"bytes,5,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	// Credentials as encrypted JSON
	CredentialsJson []byte `protobuf:"bytes,6,opt,name=credentials_json,json=credentialsJson,proto3" json:"credentials_json,omitempty"`
	// Execution policy
	Policy *StepPolicy `protobuf:"bytes,7,opt,name=policy,proto3" json:"policy,omitempty"`
	// Idempotency key for retries
	IdempotencyKey string `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Input artifacts
	InputArtifacts []*Artifact `protobuf:"bytes,9,rep,name=input_artifacts,json=inputArtifacts,proto3" json:"input_artifacts,omitempty"`
	// Additional context tags
	Tags map[string]string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Node configuration
	NodeConfigJson []byte `protobuf:"bytes,11,opt,name=node_config_json,json=nodeConfigJson,proto3" json:"node_config_json,omitempty"`
	// Parent trace context
	TraceContext  map[string]string `protobuf:"bytes,12,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecRequest) Reset() {
	*x = StepExecRequest{}
	mi := &file_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecRequest) ProtoMessage() {}

func (x *StepExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecRequest.ProtoReflect.Descriptor instead.
func (*StepExecRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{5}
}

func (x *StepExecRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StepExecRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StepExecRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepExecRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *StepExecRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *StepExecRequest) GetCredentialsJson() []byte {
	if x != nil {
		return x.CredentialsJson
	}
	return nil
}

func (x *StepExecRequest) GetPolicy() *StepPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *StepExecRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *StepExecRequest) GetInputArtifacts() []*Artifact {
	if x != nil {
		return x.InputArtifacts
	}
	return nil
}

func (x *StepExecRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StepExecRequest) GetNodeConfigJson() []byte {
	if x != nil {
		return x.NodeConfigJson
	}
	return nil
}

func (x *StepExecRequest) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

// Step execution response
type StepExecResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId    string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepId   string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Success  bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	// Output data as JSON
	OutputJson []byte `protobuf:"bytes,5,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	// Error details as JSON
	ErrorJson []byte `protobuf:"bytes,6,opt,name=error_json,json=errorJson,proto3" json:"error_json,omitempty"`
	// Error classification
	ErrorCode ErrorCode `protobuf:"varint,7,opt,name=error_code,json=errorCode,proto3,enum=n8nwork.execution.v1.ErrorCode" json:"error_code,omitempty"`
	// Performance metrics
	Metrics map[string]float64 `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Output artifacts
	OutputArtifacts []*Artifact `protobuf:"bytes,9,rep,name=output_artifacts,json=outputArtifacts,proto3" json:"output_artifacts,omitempty"`
	// Execution logs
	Logs []*LogLine `protobuf:"bytes,10,rep,name=logs,proto3" json:"logs,omitempty"`
	// Additional diagnostic information
	Diagnostics string `protobuf:"bytes,11,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	// Suggested retry delay for transient errors
	RetryAfterMs int64 `protobuf:"varint,12,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	// Execution timestamps
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecResponse) Reset() {
	*x = StepExecResponse{}
	mi := &file_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecResponse) ProtoMessage() {}

func (x *StepExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecResponse.ProtoReflect.Descriptor instead.
func (*StepExecResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{6}
}

func (x *StepExecResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StepExecResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StepExecResponse) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepExecResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StepExecResponse) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

func (x *StepExecResponse) GetErrorJson() []byte {
	if x != nil {
		return x.ErrorJson
	}
	return nil
}

func (x *StepExecResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *StepExecResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *StepExecResponse) GetOutputArtifacts() []*Artifact {
	if x != nil {
		return x.OutputArtifacts
	}
	return nil
}

func (x *StepExecResponse) GetLogs() []*LogLine {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *StepExecResponse) GetDiagnostics() string {
	if x != nil {
		return x.Diagnostics
	}
	return ""
}

func (x *StepExecResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *StepExecResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepExecResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Execution status request
type GetExecutionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusRequest) Reset() {
	*x = GetExecutionStatusRequest{}
	mi := &file_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusRequest) ProtoMessage() {}

func (x *GetExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{7}
}

func (x *GetExecutionStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetExecutionStatusRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetExecutionStatusRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

// Execution status response
type GetExecutionStatusResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	TenantId      string                            `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId         string                            `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepId        string                            `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        GetExecutionStatusResponse_Status `protobuf:"varint,4,opt,name=status,proto3,enum=n8nwork.execution.v1.GetExecutionStatusResponse_Status" json:"status,omitempty"`
	UpdatedAt     *timestamppb.Timestamp            `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Message       string                            `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string                 `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusResponse) Reset() {
	*x = GetExecutionStatusResponse{}
	mi := &file_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusResponse) ProtoMessage() {}

func (x *GetExecutionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{8}
}

func (x *GetExecutionStatusResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetStatus() GetExecutionStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetExecutionStatusResponse_STATUS_UNSPECIFIED
}

func (x *GetExecutionStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetExecutionStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Cancel execution request
type CancelExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionRequest) Reset() {
	*x = CancelExecutionRequest{}
	mi := &file_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionRequest) ProtoMessage() {}

func (x *CancelExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{9}
}

func (x *CancelExecutionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CancelExecutionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelExecutionRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *CancelExecutionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Cancel execution response
type CancelExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionResponse) Reset() {
	*x = CancelExecutionResponse{}
	mi := &file_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionResponse) ProtoMessage() {}

func (x *CancelExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionResponse.ProtoReflect.Descriptor instead.
func (*CancelExecutionResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{10}
}

func (x *CancelExecutionResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelExecutionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{11}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=n8nwork.execution.v1.HealthResponse_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Capabilities  *Capabilities          `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_execution_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_execution_proto protoreflect.FileDescriptor

const file_execution_proto_rawDesc = "" +
	"\n" +
	"\x0fexecution.proto\x12\x14n8nwork.execution.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xb7\x01\n" +
	"\vRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\"\n" +
	"\rbase_delay_ms\x18\x03 \x01(\x03R\vbaseDelayMs\x12#\n" +
	"\rjitter_factor\x18\x04 \x01(\x01R\fjitterFactor\x12 \n" +
	"\fmax_delay_ms\x18\x05 \x01(\x03R\n" +
	"maxDelayMs\"\xb2\x02\n" +
	"\n" +
	"StepPolicy\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x03R\ttimeoutMs\x12D\n" +
	"\fretry_policy\x18\x02 \x01(\v2!.n8nwork.execution.v1.RetryPolicyR\vretryPolicy\x12*\n" +
	"\x11continue_on_error\x18\x03 \x01(\bR\x0fcontinueOnError\x12S\n" +
	"\venvironment\x18\x04 \x03(\v21.n8nwork.execution.v1.StepPolicy.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x02\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12>\n" +
	"\n" +
	"data_class\x18\x03 \x01(\x0e2\x1f.n8nwork.execution.v1.DataClassR\tdataClass\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\x03R\x05bytes\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.n8nwork.execution.v1.Artifact.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\aLogLine\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12A\n" +
	"\x06fields\x18\x04 \x03(\v2).n8nwork.execution.v1.LogLine.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x03\n" +
	"\fCapabilities\x120\n" +
	"\x14supports_async_nodes\x18\x01 \x01(\bR\x12supportsAsyncNodes\x12#\n" +
	"\rsupports_wasm\x18\x02 \x01(\bR\fsupportsWasm\x12)\n" +
	"\x10supports_microvm\x18\x03 \x01(\bR\x0fsupportsMicrovm\x124\n" +
	"\x16allowed_egress_domains\x18\x04 \x03(\tR\x14allowedEgressDomains\x12<\n" +
	"\x1asupported_isolation_levels\x18\x05 \x03(\tR\x18supportedIsolationLevels\x12V\n" +
	"\fruntime_info\x18\x06 \x03(\v23.n8nwork.execution.v1.Capabilities.RuntimeInfoEntryR\vruntimeInfo\x1a>\n" +
	"\x10RuntimeInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x05\n" +
	"\x0fStepExecRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x1b\n" +
	"\tnode_type\x18\x04 \x01(\tR\bnodeType\x12\x1d\n" +
	"\n" +
	"input_json\x18\x05 \x01(\fR\tinputJson\x12)\n" +
	"\x10credentials_json\x18\x06 \x01(\fR\x0fcredentialsJson\x128\n" +
	"\x06policy\x18\a \x01(\v2 .n8nwork.execution.v1.StepPolicyR\x06policy\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12G\n" +
	"\x0finput_artifacts\x18\t \x03(\v2\x1e.n8nwork.execution.v1.ArtifactR\x0einputArtifacts\x12C\n" +
	"\x04tags\x18\n" +
	" \x03(\v2/.n8nwork.execution.v1.StepExecRequest.TagsEntryR\x04tags\x12(\n" +
	"\x10node_config_json\x18\v \x01(\fR\x0enodeConfigJson\x12\\\n" +
	"\rtrace_context\x18\f \x03(\v27.n8nwork.execution.v1.StepExecRequest.TraceContextEntryR\ftraceContext\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x05\n" +
	"\x10StepExecResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1f\n" +
	"\voutput_json\x18\x05 \x01(\fR\n" +
	"outputJson\x12\x1d\n" +
	"\n" +
	"error_json\x18\x06 \x01(\fR\terrorJson\x12>\n" +
	"\n" +
	"error_code\x18\a \x01(\x0e2\x1f.n8nwork.execution.v1.ErrorCodeR\terrorCode\x12M\n" +
	"\ametrics\x18\b \x03(\v23.n8nwork.execution.v1.StepExecResponse.MetricsEntryR\ametrics\x12I\n" +
	"\x10output_artifacts\x18\t \x03(\v2\x1e.n8nwork.execution.v1.ArtifactR\x0foutputArtifacts\x121\n" +
	"\x04logs\x18\n" +
	" \x03(\v2\x1d.n8nwork.execution.v1.LogLineR\x04logs\x12 \n" +
	"\vdiagnostics\x18\v \x01(\tR\vdiagnostics\x12$\n" +
	"\x0eretry_after_ms\x18\f \x01(\x03R\fretryAfterMs\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"h\n" +
	"\x19GetExecutionStatusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\"\xc6\x04\n" +
	"\x1aGetExecutionStatusResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12O\n" +
	"\x06status\x18\x04 \x01(\x0e27.n8nwork.execution.v1.GetExecutionStatusResponse.StatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12Z\n" +
	"\bmetadata\x18\a \x03(\v2>.n8nwork.execution.v1.GetExecutionStatusResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x04\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x05\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x06\"}\n" +
	"\x16CancelExecutionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"Q\n" +
	"\x17CancelExecutionResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xa1\x02\n" +
	"\x0eHealthResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.n8nwork.execution.v1.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\fcapabilities\x18\x03 \x01(\v2\".n8nwork.execution.v1.CapabilitiesR\fcapabilities\"h\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SERVING\x10\x01\x12\x16\n" +
	"\x12STATUS_NOT_SERVING\x10\x02\x12\x1a\n" +
	"\x16STATUS_SERVICE_UNKNOWN\x10\x03*\xf5\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fERROR_CODE_NONE\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_TRANSIENT\x10\x02\x12\x14\n" +
	"\x10ERROR_CODE_FATAL\x10\x03\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\x04\x12\x18\n" +
	"\x14ERROR_CODE_CANCELLED\x10\x05\x12\x19\n" +
	"\x15ERROR_CODE_RATE_LIMIT\x10\x06\x12\x1c\n" +
	"\x18ERROR_CODE_AUTHORIZATION\x10\a\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_INPUT\x10\b*\x98\x01\n" +
	"\tDataClass\x12\x1a\n" +
	"\x16DATA_CLASS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DATA_CLASS_GENERIC\x10\x01\x12\x12\n" +
	"\x0eDATA_CLASS_PII\x10\x02\x12\x12\n" +
	"\x0eDATA_CLASS_PHI\x10\x03\x12\x15\n" +
	"\x11DATA_CLASS_SECRET\x10\x04\x12\x18\n" +
	"\x14DATA_CLASS_FINANCIAL\x10\x052\xae\x03\n" +
	"\x10ExecutionService\x12\\\n" +
	"\vExecuteStep\x12%.n8nwork.execution.v1.StepExecRequest\x1a&.n8nwork.execution.v1.StepExecResponse\x12w\n" +
	"\x12GetExecutionStatus\x12/.n8nwork.execution.v1.GetExecutionStatusRequest\x1a0.n8nwork.execution.v1.GetExecutionStatusResponse\x12n\n" +
	"\x0fCancelExecution\x12,.n8nwork.execution.v1.CancelExecutionRequest\x1a-.n8nwork.execution.v1.CancelExecutionResponse\x12S\n" +
	"\x06Health\x12#.n8nwork.execution.v1.HealthRequest\x1a$.n8nwork.execution.v1.HealthResponseBEZCgithub.com/n8n-work/proto-contracts/gen/go/execution/v1;executionv1b\x06proto3"

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData []byte
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)))
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_execution_proto_goTypes = []any{
	(ErrorCode)(0),                         // 0: n8nwork.execution.v1.ErrorCode
	(DataClass)(0),                         // 1: n8nwork.execution.v1.DataClass
	(GetExecutionStatusResponse_Status)(0), // 2: n8nwork.execution.v1.GetExecutionStatusResponse.Status
	(HealthResponse_Status)(0),             // 3: n8nwork.execution.v1.HealthResponse.Status
	(*RetryPolicy)(nil),                    // 4: n8nwork.execution.v1.RetryPolicy
	(*StepPolicy)(nil),                     // 5: n8nwork.execution.v1.StepPolicy
	(*Artifact)(nil),                       // 6: n8nwork.execution.v1.Artifact
	(*LogLine)(nil),                        // 7: n8nwork.execution.v1.LogLine
	(*Capabilities)(nil),                   // 8: n8nwork.execution.v1.Capabilities
	(*StepExecRequest)(nil),                // 9: n8nwork.execution.v1.StepExecRequest
	(*StepExecResponse)(nil),               // 10: n8nwork.execution.v1.StepExecResponse
	(*GetExecutionStatusRequest)(nil),      // 11: n8nwork.execution.v1.GetExecutionStatusRequest
	(*GetExecutionStatusResponse)(nil),     // 12: n8nwork.execution.v1.GetExecutionStatusResponse
	(*CancelExecutionRequest)(nil),         // 13: n8nwork.execution.v1.CancelExecutionRequest
	(*CancelExecutionResponse)(nil),        // 14: n8nwork.execution.v1.CancelExecutionResponse
	(*HealthRequest)(nil),                  // 15: n8nwork.execution.v1.HealthRequest
	(*HealthResponse)(nil),                 // 16: n8nwork.execution.v1.HealthResponse
	nil,                                    // 17: n8nwork.execution.v1.StepPolicy.EnvironmentEntry
	nil,                                    // 18: n8nwork.execution.v1.Artifact.MetadataEntry
	nil,                                    // 19: n8nwork.execution.v1.LogLine.FieldsEntry
	nil,                                    // 20: n8nwork.execution.v1.Capabilities.RuntimeInfoEntry
	nil,                                    // 21: n8nwork.execution.v1.StepExecRequest.TagsEntry
	nil,                                    // 22: n8nwork.execution.v1.StepExecRequest.TraceContextEntry
	nil,                                    // 23: n8nwork.execution.v1.StepExecResponse.MetricsEntry
	nil,                                    // 24: n8nwork.execution.v1.GetExecutionStatusResponse.MetadataEntry
	(*timestamppb.Timestamp)(nil),          // 25: google.protobuf.Timestamp
}
var file_execution_proto_depIdxs = []int32{
	4,  // 0: n8nwork.execution.v1.StepPolicy.retry_policy:type_name -> n8nwork.execution.v1.RetryPolicy
	17, // 1: n8nwork.execution.v1.StepPolicy.environment:type_name -> n8nwork.execution.v1.StepPolicy.EnvironmentEntry
	1,  // 2: n8nwork.execution.v1.Artifact.data_class:type_name -> n8nwork.execution.v1.DataClass
	18, // 3: n8nwork.execution.v1.Artifact.metadata:type_name -> n8nwork.execution.v1.Artifact.MetadataEntry
	25, // 4: n8nwork.execution.v1.LogLine.timestamp:type_name -> google.protobuf.Timestamp
	19, // 5: n8nwork.execution.v1.LogLine.fields:type_name -> n8nwork.execution.v1.LogLine.FieldsEntry
	20, // 6: n8nwork.execution.v1.Capabilities.runtime_info:type_name -> n8nwork.execution.v1.Capabilities.RuntimeInfoEntry
	5,  // 7: n8nwork.execution.v1.StepExecRequest.policy:type_name -> n8nwork.execution.v1.StepPolicy
	6,  // 8: n8nwork.execution.v1.StepExecRequest.input_artifacts:type_name -> n8nwork.execution.v1.Artifact
	21, // 9: n8nwork.execution.v1.StepExecRequest.tags:type_name -> n8nwork.execution.v1.StepExecRequest.TagsEntry
	22, // 10: n8nwork.execution.v1.StepExecRequest.trace_context:type_name -> n8nwork.execution.v1.StepExecRequest.TraceContextEntry
	0,  // 11: n8nwork.execution.v1.StepExecResponse.error_code:type_name -> n8nwork.execution.v1.ErrorCode
	23, // 12: n8nwork.execution.v1.StepExecResponse.metrics:type_name -> n8nwork.execution.v1.StepExecResponse.MetricsEntry
	6,  // 13: n8nwork.execution.v1.StepExecResponse.output_artifacts:type_name -> n8nwork.execution.v1.Artifact
	7,  // 14: n8nwork.execution.v1.StepExecResponse.logs:type_name -> n8nwork.execution.v1.LogLine
	25, // 15: n8nwork.execution.v1.StepExecResponse.started_at:type_name -> google.protobuf.Timestamp
	25, // 16: n8nwork.execution.v1.StepExecResponse.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 17: n8nwork.execution.v1.GetExecutionStatusResponse.status:type_name -> n8nwork.execution.v1.GetExecutionStatusResponse.Status
	25, // 18: n8nwork.execution.v1.GetExecutionStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	24, // 19: n8nwork.execution.v1.GetExecutionStatusResponse.metadata:type_name -> n8nwork.execution.v1.GetExecutionStatusResponse.MetadataEntry
	3,  // 20: n8nwork.execution.v1.HealthResponse.status:type_name -> n8nwork.execution.v1.HealthResponse.Status
	8,  // 21: n8nwork.execution.v1.HealthResponse.capabilities:type_name -> n8nwork.execution.v1.Capabilities
	9,  // 22: n8nwork.execution.v1.ExecutionService.ExecuteStep:input_type -> n8nwork.execution.v1.StepExecRequest
	11, // 23: n8nwork.execution.v1.ExecutionService.GetExecutionStatus:input_type -> n8nwork.execution.v1.GetExecutionStatusRequest
	13, // 24: n8nwork.execution.v1.ExecutionService.CancelExecution:input_type -> n8nwork.execution.v1.CancelExecutionRequest
	15, // 25: n8nwork.execution.v1.ExecutionService.Health:input_type -> n8nwork.execution.v1.HealthRequest
	10, // 26: n8nwork.execution.v1.ExecutionService.ExecuteStep:output_type -> n8nwork.execution.v1.StepExecResponse
	12, // 27: n8nwork.execution.v1.ExecutionService.GetExecutionStatus:output_type -> n8nwork.execution.v1.GetExecutionStatusResponse
	14, // 28: n8nwork.execution.v1.ExecutionService.CancelExecution:output_type -> n8nwork.execution.v1.CancelExecutionResponse
	16, // 29: n8nwork.execution.v1.ExecutionService.Health:output_type -> n8nwork.execution.v1.HealthResponse
	26, // [26:30] is the sub-list for method output_type
	22, // [22:26] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		EnumInfos:         file_execution_proto_enumTypes,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
