# Default values for engine-go
replicaCount: 1

image:
  repository: n8n-work/engine-go
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  grpcPort: 50052
  grpcTargetPort: 50052

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: PORT
    value: "8080"
  - name: GRPC_PORT
    value: "50052"
  - name: LOG_LEVEL
    value: "info"

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsUser: 1000

persistence:
  enabled: false
  size: 10Gi
  accessMode: ReadWriteOnce